default:
  image: registry.gitlab.com/oasci/software/atomea:env
  before_script:
    - poetry install --only-root


tests:
  stage: test
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - export GOOGLE_APPLICATION_CREDENTIALS=.secure_files/atomea-691142bc6c0a.json
    - pytest -c pyproject.toml --cov=atomea --cov-report=xml --junit-xml=report.xml --color=yes tests/
    - coverage report  # for displaying coverage in job logs

    # Upload coverage to codecov
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t $CODECOV_TOKEN
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"


pages:
  stage: deploy
  script:
    - mkdocs build -d public/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
