nav:
    - Home: index.md
    - Containers:
      - containers/index.md
      - Levels:
        - containers/levels/index.md
        - Project: containers/levels/project.md
        - Ensemble: containers/levels/ensemble.md
        - Microstate: containers/levels/microstate.md
      - UUIDs: containers/uuids.md
    - Digesters: digesters
    - Examples: examples
    - API: api

sort:
  type: natural
  ignore_case: true
  by: title
  direction: asc
flatten_single_child_sections: true
