nav:
    - Home: index.md
    - Schemas: schemas
    - Digesters: digesters
    - Examples: examples
    - API: api

sort:
  type: natural
  ignore_case: true
  by: title
  direction: asc
flatten_single_child_sections: true
