name: Codecov workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    name: codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: "3.12"

      - name: Initialize conda environment
        run: make conda-create

      - name: Setup conda
        run: make conda-setup

      - name: Install conda dependencies
        run: make from-conda-lock

      - name: Install package dependencies
        run: make install

      # Setup using instructions here:
      # https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'oasci'
          workload_identity_provider: 'projects/409265393012/locations/global/workloadIdentityPools/github/providers/atomea'

      - name: Run tests and coverage
        run: make test

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
