name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Initialize conda environment
        run: make conda-create

      - name: Setup conda
        run: make conda-setup

      - name: Install conda dependencies
        run: make from-conda-lock

      - name: Poetry install
        run: make install

      # Setup using instructions here:
      # https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'oasci'
          workload_identity_provider: 'projects/409265393012/locations/global/workloadIdentityPools/github/providers/atomea'

      - name: Run tests
        run: make test
